### ISSUE TITLE
vuex-persistedstate 사용질문

### ISSUE THREAD

**Issue by ljlm0402** [pjt3591oo/vue-store-example#1]
안녕하세요! 멍게님 항상 페이스북, 블로그 좋은글에 대해 감사의 말씀드립니다.

'vuex를 이용한 store관리' 블로그 보고 코드를 참고하다 질문사항이 있어서 질문드립니다.
다름이 아니라 현재 vuex-persistedstate 사용하여 store를 관리하는데

vuex modules pattern로 작성하여 path에 적용하니

path: 'modulesName'이라고 되어있는데
그부분으로 인해

브라우저 검사에서 보면

```sh
modulesName: {
 id: '....'
}
```
처럼 나오는데

```sh
id: '...'
```
처럼 modulesName으로 감싸지 않은 형태로 보여줄려면 어떻게해야하는지 자문을 구합니다. 
해당 이유는

users 모듈패턴으로 만들어서
```sh
{
 isLogin: true,
 isLoginCode: 0
 userInfo: {
   id: 'qweqw',
   permission: 'admin'
 }
}
```
이처럼 보여주고싶기 때문입니다. 이상입니다.

**Comment by ljlm0402** [comment]
자문자답입니다.

vuex-persistedstate 모듈에 reducer 함수를 사용하면 될거같습니다.
원하실때 Close 해주시면 감사합니다.

이전 코드
```sh
plugins: [
 createPersistedState({
  key: 'users',
  paths: ['users'] // vuex modules import 값
 })
]
```

개선 코드
```sh
plugins: [
 createPersistedState({
  key: 'users',
  reducer: state => ({
   isLogin: state.user.isLogin,
   isLoginCode: state.user.isLoginCode,
   userInfo: state.user.userInfo
  })
 })
]
```

**Comment by pjt3591oo** [comment]
해결방법 찾으셔서 다행입니다 ^^
